### ISSUE TITLE
What does the property "TreatAsDesktopFullscreen" exactly do?

### ISSUE THREAD

**Issue by Aetopia** [dechamps/WindowInvestigator#3]
I have been poking around the source code of WindowInvestigator and was wondering what does "TreatAsDesktopFullscreen" exactly do?

**Comment by dechamps** [comment]
According to my reverse engineering notes, the internal `DesktopFullscreenHelpers::IsValidDesktopFullscreenWindow()` will return true if:

```
(
  GetWindowBand() == 1 &&
  GetPropW("NonRudeHWND") == 0 &&
  GetPropW("LivePreviewWindow") == 0 &&
  IsShellManagedWindow() == 0
) || GetPropW("TreatAsDesktopFullscreen") != 0
```

So I'd intuitively expect it to behave as the opposite of `NonRudeHWND` - as in, `TreatAsDesktopFullscreen` can be used to force a window to be considered "rude".

This is only my recollection from rough notes I took at the time though, so please take this with a grain of salt. In order to confirm the above I would need to dig into the binary code again, which I'm not going to do because it would take me a long time to refamiliarise myself with it since I last looked at this more than a year ago.

**Comment by Aetopia** [comment]
Thank you!
